---
- name: Update pacman cache
  become: true
  community.general.pacman:
    update_cache: true
  changed_when: false
  tags:
    - conky

- name: Install conky
  become: true
  community.general.pacman:
    name: conky
    state: present
  tags:
    - conky
