---
- include_tasks: archlinux.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: generate ~/.conkyrc
  become: false
  template:
    src: conkyrc.j2
    dest: ~/.conkyrc
  tags:
    - conky
