---
- name: Install conky
  ansible.builtin.include_tasks: install.yml
  when: install | default(true) | bool
  tags:
    - conky
    - conky:install

- name: Uninstall conky
  ansible.builtin.include_tasks: uninstall.yml
  when: not (install | default(true) | bool)
  tags:
    - conky
    - conky:uninstall
