---
- name: Uninstall conky
  become: true
  package:
    name:
      - conky
      - conky-all
    state: absent
  tags:
    - conky

- name: Destroy ~/.conkyrc
  become: false
  file:
    path: ~/.conkyrc
    state: absent
  tags:
    - conky
